server:
  tomcat:
    uri-encoding: utf-8
  port: 86
  address: 192.168.1.3
spring:
  redis:
    host: 8.134.93.52
    port: 6379
    password:
    timeout: 5000
    database: 0
    lettuce:
      pool:
        max-active: 100 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞时间
        max-idle: 100 #连接池中最大空闲连接
  rabbitmq:
    host: 112.126.76.191
    port: 5672
    username: admin
    password: 903345072
    virtual-host: my_vhost
    listener:
      direct:
        acknowledge-mode: manual
        auto-startup: false
      simple:
        auto-startup: false
        concurrency: 1
        max-concurrency: 1
        acknowledge-mode: manual #手动应答
        retry:
          enabled: true
          max-attempts: 100000
        prefetch: 1
  datasource:
    url: jdbc:mysql://localhost:3306/ziguan?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mapconfig/sqlMapConfig.xml
wwyy:
  appid: 164915
  appSecret: 3f00cad83fc94c6cb5c0c8677c839b71
widraw_fee: 3
