spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_learn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/mapper/*Mapper.xml
  config-location: classpath:mapconfig/sqlMapConfig.xml



